### ISSUE TITLE
Package version issue ?

### ISSUE THREAD

**Issue by remygrandin** [CyberShadow/steamkeyactivator#4]
Hi,

I was trying to get the software to run but I got an error while buiilding it : 
```
❯ dub build
Performing "debug" build using /home/scipio/dlang/dmd-2.094.2/linux/bin64/dmd for x86_64.
activator ~master: building configuration "application"...
../../.dub/packages/ae-0.0.2384/ae/sys/data.d(497,19): Error: declaration expected, not delete
../../.dub/packages/ae-0.0.2384/ae/sys/data.d(501,1): Error: unrecognized declaration
/home/scipio/dlang/dmd-2.094.2/linux/bin64/dmd failed with exit code 1.
```

I tried updating the ae package to the lastest version avaialable in dub.sdl (and added gcc and zlib1g-dev as dud and thelinker was complaining it was missing and then it build.

Also, not sure if related to using the updated ez package, but when running it seem to fail with or without the cookie file I placed in cookies/www.humblebundle.com.txt
```
❯ ./activator --verbose humble-bundle
Error extracting Humble Bundle keys array. Make sure you are logged in and your cookies file is up to date.
core.exception.AssertError@/home/scipio/dlang/dmd-2.094.2/linux/bin64/../../src/phobos/std/algorithm/iteration.d(627): Attempting to fetch the front of an empty map.
----------------
??:? _d_assert_msg [0x5612463bf302]
/home/scipio/dlang/dmd-2.094.2/linux/bin64/../../src/phobos/std/algorithm/iteration.d:627 nothrow @property @safe immutable(char)[] std.algorithm.iteration.MapResult!(ae.utils.regex.extractCaptures!(immutable(char)[]).extractCaptures!(immutable(char)[], std.regex.internal.ir.Regex!(char).Regex).extractCaptures(immutable(char)[], std.regex.internal.ir.Regex!(char).Regex).__lambda3, std.regex.RegexMatch!(immutable(char)[]).RegexMatch).MapResult.front() [0x561246367596]
activator.d:34 void activator.activateHBProducts() [0x5612461c936b]
activator.d:138 void activator.Activator.humbleBundle() [0x5612461ca4a4]
../../.dub/packages/ae-0.0.2845/ae/utils/funopt.d:304 void ae.utils.funopt.funopt!(activator.Activator.humbleBundle(), ae.utils.funopt.FunOptConfig(null), ae.utils.funopt.defaultUsageFun(immutable(char)[])).funopt(immutable(char)[][]) [0x561246325c7a]
../../.dub/packages/ae-0.0.2845/ae/utils/funopt.d:626 void ae.utils.funopt.funoptDispatch!(activator.Activator, ae.utils.funopt.FunOptConfig(null), ae.utils.funopt.defaultUsageFun(immutable(char)[])).funoptDispatch(immutable(char)[][]).fun(immutable(char)[], immutable(char)[][]) [0x5612463257c5]
../../.dub/packages/ae-0.0.2845/ae/utils/funopt.d:304 void ae.utils.funopt.funopt!(ae.utils.funopt.funoptDispatch!(activator.Activator, ae.utils.funopt.FunOptConfig(null), ae.utils.funopt.defaultUsageFun(immutable(char)[])).funoptDispatch(immutable(char)[][]).fun(immutable(char)[], immutable(char)[][]), ae.utils.funopt.FunOptConfig([6]), ae.utils.funopt.funoptDispatch!(activator.Activator, ae.utils.funopt.FunOptConfig(null), ae.utils.funopt.defaultUsageFun).funoptDispatch(immutable(char)[][]).myUsageFun(immutable(char)[])).funopt(immutable(char)[][]) [0x56124632a895]
../../.dub/packages/ae-0.0.2845/ae/utils/funopt.d:640 void ae.utils.funopt.funoptDispatch!(activator.Activator, ae.utils.funopt.FunOptConfig(null), ae.utils.funopt.defaultUsageFun(immutable(char)[])).funoptDispatch(immutable(char)[][]) [0x561246325613]
activator.d:171 void activator.dispatch(bool, ae.utils.funopt.OptionImpl!(2, immutable(char)[], "Action to perform (see list below)", \x00, null, null).OptionImpl, immutable(char[])[]) [0x5612461ca672]
../../.dub/packages/ae-0.0.2845/ae/utils/funopt.d:304 void ae.utils.funopt.funopt!(activator.dispatch(bool, ae.utils.funopt.OptionImpl!(2, immutable(char)[], "Action to perform (see list below)", \x00, null, null).OptionImpl, immutable(char[])[]), ae.utils.funopt.FunOptConfig(null), activator.usageFun(immutable(char)[])).funopt(immutable(char)[][]) [0x56124632d4c7]
activator.d:176 void activator.run(immutable(char)[][]) [0x5612461ca697]
../../.dub/packages/ae-0.0.2845/ae/utils/main.d:37 int activator.__mixin17.run(immutable(char)[][]) [0x5612461ca6bb]
../../.dub/packages/ae-0.0.2845/ae/utils/main.d:45 int activator.__mixin17.runCatchingException!(std.getopt.GetOptException, "Usage error").runCatchingException(immutable(char)[][]) [0x56124620bb6f]
../../.dub/packages/ae-0.0.2845/ae/utils/main.d:70 _Dmain [0x5612461ca6df]
```

Do you have an idea of what went wrong ?

**Comment by CyberShadow** [comment]
Just some bitrot :)

Should be fixed now.

**Comment by remygrandin** [comment]
Tip top,
All is running good. 
Thanks for the ligntning fast response ^^

**Comment by CyberShadow** [comment]
Thanks for the detailed bug report :)

**Comment by remygrandin** [comment]
Woops, I was a bit too fast to respond.

The humble key dump worked but then it fail at the first steam key activation try (I jumbled the key and session id): 
```
Got Steam session ID: XXXXXXXXXXXXXXXXXXXXXXXXX
[1/1155] Activating Steam key: XXXXX-YYYYY-ZZZZZ (Safecracker: The Ultimate Puzzle Adventure)
Error extracting Humble Bundle keys array. Make sure you are logged in and your cookies file is up to date.
std.json.JSONException@std/json.d(1730): Unexpected character '<'. (Line 1:1)
----------------
/home/scipio/dlang/dmd-2.094.2/linux/bin64/../../src/phobos/std/json.d:937 pure @safe void std.json.parseJSON!(immutable(char)[]).parseJSON(immutable(char)[], int, std.json.JSONOptions).error(immutable(char)[]) [0x55f418476358]
/home/scipio/dlang/dmd-2.094.2/linux/bin64/../../src/phobos/std/json.d:1359 pure @safe void std.json.parseJSON!(immutable(char)[]).parseJSON(immutable(char)[], int, std.json.JSONOptions).parseValue(ref std.json.JSONValue) [0x55f418477146]
/home/scipio/dlang/dmd-2.094.2/linux/bin64/../../src/phobos/std/json.d:1365 pure @safe std.json.JSONValue std.json.parseJSON!(immutable(char)[]).parseJSON(immutable(char)[], int, std.json.JSONOptions) [0x55f4184762b8]
activator.d:103 void activator.activateSteamKeys(activator.SteamKey[]) [0x55f418448003]
activator.d:71 void activator.activateHBKeys(immutable(char)[][]) [0x55f418447abe]
activator.d:39 void activator.activateHBProducts() [0x55f4184473f8]
activator.d:138 void activator.Activator.humbleBundle() [0x55f4184484c4]
../../.dub/packages/ae-0.0.2845/ae/utils/funopt.d:304 void ae.utils.funopt.funopt!(activator.Activator.humbleBundle(), ae.utils.funopt.FunOptConfig(null), ae.utils.funopt.defaultUsageFun(immutable(char)[])).funopt(immutable(char)[][]) [0x55f4185a3cfe]
../../.dub/packages/ae-0.0.2845/ae/utils/funopt.d:626 void ae.utils.funopt.funoptDispatch!(activator.Activator, ae.utils.funopt.FunOptConfig(null), ae.utils.funopt.defaultUsageFun(immutable(char)[])).funoptDispatch(immutable(char)[][]).fun(immutable(char)[], immutable(char)[][]) [0x55f4185a3849]
../../.dub/packages/ae-0.0.2845/ae/utils/funopt.d:304 void ae.utils.funopt.funopt!(ae.utils.funopt.funoptDispatch!(activator.Activator, ae.utils.funopt.FunOptConfig(null), ae.utils.funopt.defaultUsageFun(immutable(char)[])).funoptDispatch(immutable(char)[][]).fun(immutable(char)[], immutable(char)[][]), ae.utils.funopt.FunOptConfig([6]), ae.utils.funopt.funoptDispatch!(activator.Activator, ae.utils.funopt.FunOptConfig(null), ae.utils.funopt.defaultUsageFun).funoptDispatch(immutable(char)[][]).myUsageFun(immutable(char)[])).funopt(immutable(char)[][]) [0x55f4185a8919]
../../.dub/packages/ae-0.0.2845/ae/utils/funopt.d:640 void ae.utils.funopt.funoptDispatch!(activator.Activator, ae.utils.funopt.FunOptConfig(null), ae.utils.funopt.defaultUsageFun(immutable(char)[])).funoptDispatch(immutable(char)[][]) [0x55f4185a3697]
activator.d:173 void activator.dispatch(bool, ae.utils.funopt.OptionImpl!(2, immutable(char)[], "Action to perform (see list below)", \x00, null, null).OptionImpl, immutable(char[])[]) [0x55f4184486f2]
../../.dub/packages/ae-0.0.2845/ae/utils/funopt.d:304 void ae.utils.funopt.funopt!(activator.dispatch(bool, ae.utils.funopt.OptionImpl!(2, immutable(char)[], "Action to perform (see list below)", \x00, null, null).OptionImpl, immutable(char[])[]), ae.utils.funopt.FunOptConfig(null), activator.usageFun(immutable(char)[])).funopt(immutable(char)[][]) [0x55f4185ab54b]
activator.d:178 void activator.run(immutable(char)[][]) [0x55f41844871b]
../../.dub/packages/ae-0.0.2845/ae/utils/main.d:37 int activator.__mixin17.run(immutable(char)[][]) [0x55f41844873f]
../../.dub/packages/ae-0.0.2845/ae/utils/main.d:45 int activator.__mixin17.runCatchingException!(std.getopt.GetOptException, "Usage error").runCatchingException(immutable(char)[][]) [0x55f418489bf3]
../../.dub/packages/ae-0.0.2845/ae/utils/main.d:70 _Dmain [0x55f418448763]
```

**Comment by CyberShadow** [comment]
Hmm, the Steam side is still working for me. Is [the web page](https://store.steampowered.com/account/registerkey) loading for you?

Perhaps try running with `--verbose` and see if the server is returning some HTTP error?

**Comment by remygrandin** [comment]
Yes the page is loading fine. I've tried to re-copy the cookies, to no avail.
What may be changing is the page is loading in french with my session in my browser (but the cache files seem to be in english tho...)
I've had to shoot the cache to have any different output with the verbose.
It dont seem to be responding with an HTTP error.

```
> GET /account/registerkey HTTP/1.1
Host: store.steampowered.com
User-Agent: Phobos-std.net.curl/2.094 (libcurl/7.68.0)
Accept: */*
Cookie: very_long_cookies_string

* old SSL session ID is stale, removing
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Server: nginx
< Content-Type: text/html; charset=UTF-8
< Expires: Mon, 26 Jul 1997 05:00:00 GMT
< Cache-Control: no-cache
< Content-Security-Policy: default-src blob: data: https: 'unsafe-inline' 'unsafe-eval'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://store.cloudflare.steamstatic.com/ https://store.cloudflare.steamstatic.com/ *.google-analytics.com https://www.gstatic.com; object-src 'none'; connect-src 'self' http://store.steampowered.com https://store.steampowered.com http://127.0.0.1:27060 ws://127.0.0.1:27060 https://community.cloudflare.steamstatic.com/ https://steamcommunity.com/ https://steamcommunity.com/ wss://community.steam-api.com/websocket/ https://api.steampowered.com/ *.google-analytics.com; frame-src 'self' steam:  http://www.youtube.com https://www.youtube.com https://www.google.com https://sketchfab.com https://player.vimeo.com https://steamcommunity.com/ https://steamcommunity.com/;
< X-Frame-Options: DENY
< Strict-Transport-Security: max-age=300
< Date: Sun, 29 Nov 2020 18:29:10 GMT
< Content-Length: 70904
< Connection: keep-alive
<
* Connection #1 to host store.steampowered.com left intact
Got Steam session ID: xxxxxxxxxxxxxxxxxxxxxxx
[1/1155] Activating Steam key: XXXXX-YYYYY-ZZZZZ (Safecracker: The Ultimate Puzzle Adventure)
Error extracting Humble Bundle keys array. Make sure you are logged in and your cookies file is up to date.
std.json.JSONException@std/json.d(1730): Unexpected character '<'. (Line 1:1)
----------------
/home/scipio/dlang/dmd-2.094.2/linux/bin64/../../src/phobos/std/json.d:937 pure @safe void std.json.parseJSON!(immutable(char)[]).parseJSON(immutable(char)[], int, std.json.JSONOptions).error(immutable(char)[]) [0x5559883ba358]
/home/scipio/dlang/dmd-2.094.2/linux/bin64/../../src/phobos/std/json.d:1359 pure @safe void std.json.parseJSON!(immutable(char)[]).parseJSON(immutable(char)[], int, std.json.JSONOptions).parseValue(ref std.json.JSONValue) [0x5559883bb146]
/home/scipio/dlang/dmd-2.094.2/linux/bin64/../../src/phobos/std/json.d:1365 pure @safe std.json.JSONValue std.json.parseJSON!(immutable(char)[]).parseJSON(immutable(char)[], int, std.json.JSONOptions) [0x5559883ba2b8]
activator.d:103 void activator.activateSteamKeys(activator.SteamKey[]) [0x55598838c003]
activator.d:71 void activator.activateHBKeys(immutable(char)[][]) [0x55598838babe]
activator.d:39 void activator.activateHBProducts() [0x55598838b3f8]
activator.d:138 void activator.Activator.humbleBundle() [0x55598838c4c4]
../../.dub/packages/ae-0.0.2845/ae/utils/funopt.d:304 void ae.utils.funopt.funopt!(activator.Activator.humbleBundle(), ae.utils.funopt.FunOptConfig(null), ae.utils.funopt.defaultUsageFun(immutable(char)[])).funopt(immutable(char)[][]) [0x5559884e7cfe]
../../.dub/packages/ae-0.0.2845/ae/utils/funopt.d:626 void ae.utils.funopt.funoptDispatch!(activator.Activator, ae.utils.funopt.FunOptConfig(null), ae.utils.funopt.defaultUsageFun(immutable(char)[])).funoptDispatch(immutable(char)[][]).fun(immutable(char)[], immutable(char)[][]) [0x5559884e7849]
../../.dub/packages/ae-0.0.2845/ae/utils/funopt.d:304 void ae.utils.funopt.funopt!(ae.utils.funopt.funoptDispatch!(activator.Activator, ae.utils.funopt.FunOptConfig(null), ae.utils.funopt.defaultUsageFun(immutable(char)[])).funoptDispatch(immutable(char)[][]).fun(immutable(char)[], immutable(char)[][]), ae.utils.funopt.FunOptConfig([6]), ae.utils.funopt.funoptDispatch!(activator.Activator, ae.utils.funopt.FunOptConfig(null), ae.utils.funopt.defaultUsageFun).funoptDispatch(immutable(char)[][]).myUsageFun(immutable(char)[])).funopt(immutable(char)[][]) [0x5559884ec919]
../../.dub/packages/ae-0.0.2845/ae/utils/funopt.d:640 void ae.utils.funopt.funoptDispatch!(activator.Activator, ae.utils.funopt.FunOptConfig(null), ae.utils.funopt.defaultUsageFun(immutable(char)[])).funoptDispatch(immutable(char)[][]) [0x5559884e7697]
activator.d:173 void activator.dispatch(bool, ae.utils.funopt.OptionImpl!(2, immutable(char)[], "Action to perform (see list below)", \x00, null, null).OptionImpl, immutable(char[])[]) [0x55598838c6f2]
../../.dub/packages/ae-0.0.2845/ae/utils/funopt.d:304 void ae.utils.funopt.funopt!(activator.dispatch(bool, ae.utils.funopt.OptionImpl!(2, immutable(char)[], "Action to perform (see list below)", \x00, null, null).OptionImpl, immutable(char[])[]), ae.utils.funopt.FunOptConfig(null), activator.usageFun(immutable(char)[])).funopt(immutable(char)[][]) [0x5559884ef54b]
activator.d:178 void activator.run(immutable(char)[][]) [0x55598838c71b]
../../.dub/packages/ae-0.0.2845/ae/utils/main.d:37 int activator.__mixin17.run(immutable(char)[][]) [0x55598838c73f]
../../.dub/packages/ae-0.0.2845/ae/utils/main.d:45 int activator.__mixin17.runCatchingException!(std.getopt.GetOptException, "Usage error").runCatchingException(immutable(char)[][]) [0x5559883cdbf3]
../../.dub/packages/ae-0.0.2845/ae/utils/main.d:70 _Dmain [0x55598838c763]
```


I've attached what I belive to be the cache file for the request
[21E6340858E974F95544A9DC3031BB83.txt](https://github.com/CyberShadow/steamkeyactivator/files/5612667/21E6340858E974F95544A9DC3031BB83.txt)

**Comment by CyberShadow** [comment]
OK, I found the problem and pushed a fix (my previous fix was incomplete), can you try it now?

**Comment by remygrandin** [comment]
Yes, seems ok, i've tested a few keys and hit the throttle limit, so look good to me
